import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "./(Home)/components/layout/Header";

const montserrat = Montserrat({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Lunatic Eclipse Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${montserrat.className} `}>
        <video
          autoPlay
          muted
          loop
          id="myVideo"
          className="w-full h-full -z-10 fixed left-0 top-0 object-center object-cover "
        >
          <source src="/WebSite/Webarkaplan.mp4" type="video/mp4" />
        </video>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
