import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import Navbar from "./(Home)/components/layout/Header";
import LoaderProvider from "./(Home)/components/layout/LoaderProvider";

const montserrat = Montserrat({ subsets: ["latin"] });
export const metadata: Metadata = {
  title: "Lunatic Eclipse Studio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={`${montserrat.className} bg-black`}>
        <LoaderProvider>
          <Navbar />
          {children}
        </LoaderProvider>
      </body>
    </html>
  );
}
